name: AI News Intelligence Agent

on:
  schedule:
    - cron: '0 8 * * 1-5'  # Daily at 8 AM UTC, weekdays only
    - cron: '0 9 * * 0'    # Weekly summary on Sunday at 9 AM UTC
  workflow_dispatch:
    inputs:
      mode:
        description: 'Run mode'
        required: true
        default: 'daily'
        type: choice
        options:
        - daily
        - weekly

jobs:
  run-ai-news-agent:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run AI News Agent
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: |
        if [ "${{ github.event.inputs.mode }}" = "weekly" ] || [ "${{ github.event.schedule }}" = "0 9 * * 0" ]; then
          python ai_news_agent.py weekly
        else
          python ai_news_agent.py daily
        fi
        
    - name: Generate Dashboard Data
      run: python generate_dashboard_data.py
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dashboard
